kettle:
  log-file-path: /apps/logs/${spring.application.name}/run-logs
  encoding: utf-8
  upload-path: /apps/var/kettle-script-file
  kettle-home: /apps/var/file-rep
  vm-url: http://10.108.8.30:8080/sqlManager/mv/Refresh?tagId=