server:
  port: 7080
  servlet: # 访问路径
    context-path: /
  tomcat:
    uri-encoding: UTF-8 # get请求中文乱码配置
mybatis:
  configuration:
    map-underscore-to-camel-case: 'true'
spring:
  application:
    name: kettle-scheduler
  profiles:
    active: dev # 激活分支
    include: # 引入自定义配置文件
      - swagger
      - shiro
      - kettle
  aop: # 设置动态代理方式为cglib，否在shiro代理会失败
    proxy-target-class: true
  redis:
    database: 0
    host: 120.79.236.37
    password: sms123
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 100
        max-idle: 3
        max-wait: -1
        min-idle: 0
  rabbitmq:
    password: 123456
    username: admin
    port: 5672
    addresses: 10.108.6.118
    #开启发送失败返回
    publisher-returns: true
    #开启发送确认
    publisher-confirms: true
    listener:
      simple:
        #指定最小的消费者数量.
        concurrency: 2
        #指定最大的消费者数量.
        max-concurrency: 2
        #开启ack
        acknowledge-mode: auto
      #开启ack
      direct:
        acknowledge-mode: auto
    #支持消息的确认与返回
    template:
      mandatory: true
  http:
    encoding: # post请求中文乱码配置
      enabled: true
      charset: UTF-8
      force: true
      force-request: true
      force-response: true
  mvc: # 日期转换
    date-format: yyyy-MM-dd HH:mm:ss
  jackson: # json日期转换
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always #json格式化的时候不显示值为空的属性字段
  data:
    redis:
      repositories:
        enabled: false #关闭redis持久化,只做缓存使用
  servlet:
    multipart: # 上传文件大小配置
      max-file-size: 2MB
      max-request-size: 10MB
constant:
  salt: kettle-salt
  hash-iterations: 10