spring:
  datasource: # 数据库链接
    #url: jdbc:mysql://120.79.236.37/kettle-scheduler?serverTimezone=UTC&useSSL=false
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: kettle_scheduler
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
    #driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true # sql打印
    #database-platform: org.hibernate.dialect.MySQLDialect # 数据库方言
    open-in-view: false # false关闭懒加载
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  thymeleaf:
    cache: false #开发过程关闭页面缓存
logging: # 日志记录
  level:
    root: info
    org.kettle.scheduler: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace # 打印sql参数
  file: /apps/logs/${spring.application.name}/${spring.application.name}.log
thread:
  refreshMview:
    corePoolSize: 10
    maxPoolSize: 50
    queueCapacity: 500
    keepAliveSeconds: 10
  downloadFtpFile:
    corePoolSize: 2
    maxPoolSize: 4
    queueCapacity: 200
    keepAliveSeconds: 10
  implDb:
    corePoolSize: 1
    maxPoolSize: 2
    queueCapacity: 200
    keepAliveSeconds: 10
xxl:
  job:
    accessToken:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: kettle-scheduler
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 19999